### ISSUE TITLE
API call returning not found when it should exist

### ISSUE THREAD

**Issue by mchuahua** [DonneyF/ubc-pair-grade-data#1]
Hi Donney,

I'm seeing this API call 

`https://ubcgrades.com/api/v2/grades/UBCV/2022W/EECE/599/OVERALL` returning `{"error":"Not Found","message":"Not Found"}` 

instead of 

`{"average":86.4222222222222,"campus":"UBCV","course":"599","course_title":"Thesis","detail":"","educators":null,"faculty_title":"Faculty of Applied Science","grades":{"50-54%":0,"55-59%":0,"60-63%":0,"64-67%":0,"68-71%":0,"72-75%":1,"76-79%":4,"80-84%":5,"85-89%":11,"90-100%":6,"<50%":0},"high":96,"low":73,"median":null,"percentile_25":null,"percentile_75":null,"reported":27,"section":"OVERALL","session":"W","subject":"EECE","subject_title":"Electrical and Computer Engineering","year":"2022"}` 

as similarly expected with v3. Other courses seem to work though, but I'm unable to test extensively. 

Since v3 only carries data from 2019W onward, I stuck with v2 for my transcript extension since some people have grades before 2019W. 

Cheers,
Martin

**Comment by mchuahua** [comment]
Nevermind, using course statistics is better anyways for my usecase, sorry!

**Comment by DonneyF** [comment]
Hi Martin,

The v2 endpoint for [DonneyF/ubcgrades](https://github.com/DonneyF/ubcgrades) corresponds to the Tableau Dashboard v1 dataset in this repo, which provided data only up to 2021W. If you needed anything newer you'd have to use v3.

You might be interested in this code snippet, which was how I decided to select each endpoint depending on the year: 

https://github.com/DonneyF/ubcgrades/blob/d75926b963e7bb3765af9ab0c6831e1deeb66405/app/static/assets/js/view-grades.js#L205-L211

This isn't clear on the API documentation page, I'll get around to cleaning up that page later.
